### ISSUE TITLE
Valid move of pawn

### ISSUE THREAD

**Issue by JiZur** [plemaster01/pygameChess#2]
Hi, I have a question rearding the displacement of pawns. When the pawn is on its initial position and wants to move forward by 2 tiles, shouldn't it be free of ally/ennemy on both the 2 tiles forward and not only the arrival one (it can't jump over another piece, isn't it?)?

Thanks for the excellent video and the code on GitHub :)

**Comment by plemaster01** [comment]
Hi Jimmy,Adding Castling, Pawn Promotion and En Passant to Chess in Python!https://youtu.be/s2Dd_obh3fMI suggest checking out the follow up video where this and more features were addressed. Thanks,Pete - LeMaster Tech Sent from my iPhoneOn Nov 22, 2023, at 1:42 PM, Jimmy Zurcher ***@***.***> wrote:﻿
Hi, I have a question rearding the displacement of pawns. When the pawn is on its initial position and wants to move forward by 2 tiles, shouldn't it be free of ally/ennemy on both the 2 tiles forward and not only the arrival one?
Thanks for the excellent video and the code on GitHub :)

**Comment by JiZur** [comment]
I see, indeed event though I did not notice in the second video, the code in the additions file is checking the valid moves for pawn differently. Thanks for taking the time to answer and sorry for the "false alarm" type of comment :)
